name: bitacora
description: "Bitácora de préstamo de llaves."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  go_router: ^14.3.0
  http: ^1.2.2
  path: ^1.9.0
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  test: ^1.25.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bitacora.db

  fonts:
    - family: Baloo 2
      fonts:
        - asset: fonts/Baloo2-variable.ttf
