name: bitacora
description: "Bitácora de préstamo de llaves."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  go_router: ^14.3.0
  http: ^1.2.2
  path: ^1.9.0
  sqflite: ^2.4.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  excel: ^4.0.6
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  test: ^1.25.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bitacora.db
    - assets/logo.png

  fonts:
    - family: Baloo 2
      fonts:
        - asset: fonts/Baloo2-variable.ttf

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#f5f5f5"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#f5f5f5"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#f5f5f5"